name: Ruby CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # lub inna wersja

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests (Minitest)
        run: bundle exec rake test
